services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: node server.js
    restart: always
    env_file:
      - .env

  python_service:
    build: ./python_service
    ports:
      - "5001:5001"
    volumes:
      - ./python_service:/app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 5001 --reload
    restart: always
    env_file:
      - .env
